// Generated by dts-bundle v0.7.3

declare module 'index' {
    export * from 'index/StudentVue/StudentVue.interfaces';
    export * from 'index/StudentVue/StudentVue';
    export * from 'index/StudentVue/Client/Client';
    export * from 'index/StudentVue/Client/Client.interfaces';
}

declare module 'index/StudentVue/StudentVue.interfaces' {
    export interface SchoolDistrict {
        address: string;
        id: string;
        name: string;
        parentVueUrl: string;
    }
    
    export interface UserCredentials {
        username: string;
        password: string;
    }
}

declare module 'index/StudentVue/StudentVue' {
    import { SchoolDistrict, UserCredentials } from 'index/StudentVue/StudentVue.interfaces';
    import Client from 'index/StudentVue/Client/Client';
    export default class StudentVue {
        static login(districtUrl: string, credentials: UserCredentials): Promise<Client>;
        static findDistricts(zipCode: string): Promise<SchoolDistrict[]>;
    }
}

declare module 'index/StudentVue/Client/Client' {
    import soap from 'index/utils/soap/soap';
    export default class Client extends soap.Client {
        constructor(username: string, password: string);
    }
}

declare module 'index/StudentVue/Client/Client.interfaces' {
    export interface StudentInfo {
        nickname: string;
    }
    
    export * from 'index/StudentVue/Client/Client';
}

declare module 'index/utils/soap/soap' {
    import Client from 'index/utils/soap/Client/Client';
    const _default: {
        Client: typeof Client;
    };
    export default _default;
}

declare module 'index/utils/soap/Client/Client' {
    import { RequestOptions } from 'index/utils/soap/Client/Client.interfaces';
    export default class Client {
        protected get username(): string;
        protected get password(): string;
        constructor(username: string, password: string);
        protected processRequest<T>(): Promise<T>;
        protected processAnonymousRequest<T>(options?: RequestOptions): Promise<T>;
    }
}

declare module 'index/utils/soap/Client/Client.interfaces' {
    export interface RequestOptions {
        skipLoginLog?: number;
        parent?: number;
        webServiceHandleName?: string;
        methodName?: string;
        paramStr?: Record<string, unknown>;
    }
}

